[package]
name = "workstations"
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = "2.1.0"
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.0", features = ["signal"] }
tokio-signal = "0.2.9"

