// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: fault_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaultService_GetFaults_FullMethodName = "/FaultInterface.FaultService/GetFaults"
)

// FaultServiceClient is the client API for FaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaultServiceClient interface {
	GetFaults(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FaultResponse, error)
}

type faultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaultServiceClient(cc grpc.ClientConnInterface) FaultServiceClient {
	return &faultServiceClient{cc}
}

func (c *faultServiceClient) GetFaults(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FaultResponse)
	err := c.cc.Invoke(ctx, FaultService_GetFaults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaultServiceServer is the server API for FaultService service.
// All implementations must embed UnimplementedFaultServiceServer
// for forward compatibility.
type FaultServiceServer interface {
	GetFaults(context.Context, *Empty) (*FaultResponse, error)
	mustEmbedUnimplementedFaultServiceServer()
}

// UnimplementedFaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaultServiceServer struct{}

func (UnimplementedFaultServiceServer) GetFaults(context.Context, *Empty) (*FaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFaults not implemented")
}
func (UnimplementedFaultServiceServer) mustEmbedUnimplementedFaultServiceServer() {}
func (UnimplementedFaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeFaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaultServiceServer will
// result in compilation errors.
type UnsafeFaultServiceServer interface {
	mustEmbedUnimplementedFaultServiceServer()
}

func RegisterFaultServiceServer(s grpc.ServiceRegistrar, srv FaultServiceServer) {
	// If the following call pancis, it indicates UnimplementedFaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaultService_ServiceDesc, srv)
}

func _FaultService_GetFaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultServiceServer).GetFaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaultService_GetFaults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultServiceServer).GetFaults(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FaultService_ServiceDesc is the grpc.ServiceDesc for FaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FaultInterface.FaultService",
	HandlerType: (*FaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFaults",
			Handler:    _FaultService_GetFaults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fault_service.proto",
}
