version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq2/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq2
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379
    networks:
      - app-network
    restart: unless-stopped

  go_app:
    build:
      context: ./fault_detection
      dockerfile: Dockerfile
    container_name: "go_app"
    volumes:
      - ./fault_detection/logs:/app/logs
      - ./Client/log.txt:/app/logs/FaultDetector.log
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client_app:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: "client_app"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: unless-stopped

  agvs:
    build:
      context: ./Robotics/AGV
      dockerfile: Dockerfile
    container_name: "agv"
    volumes:
      - ./Robotics/AGV/log:/app/log
      - ./Client/log.txt:/app/log/agv.log
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  workstations:
    build:
      context: ./Robotics/Workstations
      dockerfile: Dockerfile
    container_name: "workstations"
    volumes:
      - ./Robotics/Workstations/log:/app/log
      - ./Client/log.txt:/app/log/workstations.log
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  orch_app:
    build:
      context: ./App
      dockerfile: Dockerfile
    container_name: "orch_app"
    volumes:
      - ./App/logged:/app/logged
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network
    ports:
      - "8080:5000"
      - "50051:50051"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
